# -*- coding: utf-8 -*-
"""GenerateQRCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPKQul7kWdwRo_hBxn_Ak_oGRQV2zFjC
"""

pip install pyqrcode

import pyqrcode

s = "www.google.com"
url = pyqrcode.create(s)
url.svg("myqr.svg", scale = 8)